version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_lucky_wheel
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-k_tech_lucky_wheel}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Admin@123}
      - POSTGRES_DB=${POSTGRES_DB:-lucky_wheel_database}
    volumes:
      - postgres_data:/var/lib/postgresql/k_tech_lucky_wheel/data
    ports:
      - "5436:5432"
    restart: always
volumes:
  postgres_data:

networks:
  strapi:
    name: Strapi
    driver: bridge
